export const CardDetails = [
  // hospital
  // clinic
  // ambulance

  {
    id: 1,
    Name: "কর্নেল মালেক মেডিকেল কলেজ,মানিকগঞ্জ",
    MobileNumber: "01711960552",
    token: "হাসপাতাল",
  },
  {
    id: 2,
    Name: "২৫০ শয্যা জেলা হাসপাতাল, মানিকগঞ্জ",
    MobileNumber: "027710778",
    token: "হাসপাতাল",
  },
  {
    id: 3,
    Name: "মানিকগঞ্জ ডায়াবেটিক হাসপাতাল",
    MobileNumber: "01xxxxxxxxxxx",
    token: "হাসপাতাল",
  },
  {
    id: 4,
    Name: "সিংগাইর উপজেলা হেলথ কমপ্লেক্ম",
    MobileNumber: "01xxxxxxxxxxx",
    token: "হাসপাতাল",
  },
  {
    id: 5,
    Name: "শান্তিপুর হেলথ কমপ্লেক্ম, সিংগাইর",
    MobileNumber: "01xxxxxxxxxxx",
    token: "হাসপাতাল",
  },
  {
    id: 6,
    Name: "মানিকগঞ্জ সদর হাসপাতাল",
    MobileNumber: "027710778",
    token: "হাসপাতাল",
  },
  {
    id: 7,
    Name: "সাটুরিয়া হেলথ কমপ্লেক্ম",
    MobileNumber: "01xxxxxxxxxxx",
    token: "হাসপাতাল",
  },
  {
    id: 8,
    Name: "শিবালয় হেলথ কমপ্লেক্ম",
    MobileNumber: "01xxxxxxxxxxx",
    token: "হাসপাতাল",
  },
  {
    id: 9,
    Name: "৫০ শয্যা বিশিষ্ট ঘিওর উপজেলা স্বাস্থ্য কমপ্লেক্স",
    MobileNumber: "01xxxxxxxxxxx",
    token: "হাসপাতাল",
  },
  {
    id: 10,
    Name: "উপজেলা স্বাস্থ্য কমপ্লেক্স, দৌলতপুর",
    MobileNumber: "01xxxxxxxxxxx",
    token: "হাসপাতাল",
  },

  {
    id: 11,
    Name: "ইসলামি ব্যাংক কমিউনিটি হাসপাতাল, মানিকগঞ্জ",
    MobileNumber: "01817533724",
    token: "ক্লিনিক",
  },
  {
    id: 12,
    Name: "সরকারি দেবেন্দ্র কলেজ, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 13,
    Name: "মানিকগঞ্জ ইউনাইটেড হাসপাতাল",
    MobileNumber: "01711676398",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "জম জম জেনারেল হাসপাতাল, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 15,
    Name: "মানিকগঞ্জ সেন্ট্রাল স্পেশালাইজড হাসপাতাল",
    MobileNumber: "01789176311",
    token: "ক্লিনিক",
  },
  {
    id: 16,
    Name: "শাপলা মেডিকেল সেন্টার",
    MobileNumber: "01711285633",
    token: "ক্লিনিক",
  },
  {
    id: 17,
    Name: "মেডিল্যাব জেনারেল হাসপাতাল",
    MobileNumber: "027711279",
    token: "ক্লিনিক",
  },
  {
    id: 18,
    Name: "জনকল্যান নার্সিং হোম",
    MobileNumber: "01558697322",
    token: "ক্লিনিক",
  },
  {
    id: 19,
    Name: "যমুনা জেনারেল হাসপাতাল",
    MobileNumber: "01727119807",
    token: "ক্লিনিক",
  },
  {
    id: 20,
    Name: "পল্লীস্বাস্থ্য মেডিটেক ইন্সটিটিউট ও হাসপাতাল লিঃ",
    MobileNumber: " 01715246763",
    token: "ক্লিনিক",
  },
  {
    id: 21,
    Name: "মানিকগঞ্জ লাইফ কেয়ার হাসপাতাল",
    MobileNumber: "01904654501",
    token: "ক্লিনিক",
  },
  {
    id: 22,
    Name: "হেলথ কেয়ার মেডিক্যাল সেন্টার",
    MobileNumber: "01924874409",
    token: "ক্লিনিক",
  },
  {
    id: 24,
    Name: "দোয়েল মেডিকেল সেন্টার",
    MobileNumber: "01712632229",
    token: "ক্লিনিক",
  },
  {
    id: 25,
    Name: "দারুস সালাম ডায়াগনস্টিক সেন্টার",
    MobileNumber: "01712074425",
    token: "ক্লিনিক",
  },
  {
    id: 26,
    Name: "ম্যাটারনিটি হাসপাতাল, মানিকগঞ্জ",
    MobileNumber: "01711102296",
    token: "হাসপাতাল",
  },
  {
    id: 27,
    Name: "নিরাময় নার্সিং এন্ড ডায়াগনস্টিক",
    MobileNumber: "01711272584",
    token: "ক্লিনিক",
  },
  {
    id: 27,
    Name: "মাহিন ডেন্টাল কেয়ার",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 29,
    Name: "মানিকগঞ্জ অ্যাপোলো হাসপাতাল",
    MobileNumber: "01711076960",
    token: "ক্লিনিক",
  },
  {
    id: 30,
    Name: "আল শেফা এক্স-রে এন্ড প্যাথলজি",
    MobileNumber: "01733255605",
    token: "ক্লিনিক",
  },
  {
    id: 31,
    Name: "ডায়মন্ড ডায়াগনস্টিক সেন্টার এবং হাসপাতাল",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 32,
    Name: "পপুলার ক্লিনিক",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 33,
    Name: "গ্রীন লাইফ হাসপাতাল এবং ল্যাব",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 34,
    Name: "নুরজাহান জেনারেল হাসপাতাল",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 35,
    Name: "ফিরোজা জেনারেল হাসপাতাল & ডায়াগনস্টিক সেন্টার",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 36,
    Name: "বলাকা জেনারেল হাসপাতাল",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 37,
    Name: "মমতাজ চক্ষু হাসপাতাল",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 38,
    Name: "সূর্যমুখী চক্ষু হাসপাতাল",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 39,
    Name: "ইউনাইটেড জেনারেল হাসপাতাল",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 40,
    Name: "সাহেরা হাসান মেমোরিয়াল হাসপাতাল",
    MobileNumber: "01712099178",
    token: "ক্লিনিক",
  },
  {
    id: 41,
    Name: "খানবাহাদুর আওলাদ হোসেন খান কলেজ, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 42,
    Name: "মানিকগঞ্জ টেকনিক্যাল স্কুল এন্ড কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 43,
    Name: "মানিকগঞ্জ টেক্সটাইল ভোকেশনাল",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 44,
    Name: "মানিকগঞ্জ মহিলা কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 45,
    Name: "ফায়ার সার্ভিস স্টেশন,মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ফায়ার সার্ভিস",
  },
  {
    id: 46,
    Name: "ফায়ার সার্ভিস এন্ড সিভিল ডিফেন্স স্টেশন, দৌলতপুর",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ফায়ার সার্ভিস",
  },
  {
    id: 47,
    Name: "সাটুরিয়া ফায়ার স্টেশন, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ফায়ার সার্ভিস",
  },
  {
    id: 48,
    Name: "ঘিওর ফায়ার স্টেশন, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ফায়ার সার্ভিস",
  },
  {
    id: 49,
    Name: "ফায়ার সার্ভিস ও সিভিল ডিফেন্স স্টেশন, সিংগাইর",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ফায়ার সার্ভিস",
  },
  {
    id: 50,
    Name: "হরিরামপুর ফায়ার সার্ভিস স্টেশন, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ফায়ার সার্ভিস",
  },
  {
    id: 51,
    Name: "ফায়ার সার্ভিস স্টেশন, শিবালয়",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ফায়ার সার্ভিস",
  },
  {
    id: 52,
    Name: "ফায়ার প্রটেকশন সিস্টেম সাপ্লায়ার, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ফায়ার সার্ভিস",
  },
  {
    id: 53,
    Name: "মানিকগঞ্জ সদর থানা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পুলিশ স্টেশন",
  },
  {
    id: 54,
    Name: "মানিকগঞ্জ পুলিশ লাইন",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পুলিশ স্টেশন",
  },
  {
    id: 55,
    Name: "হরিরামপুর থানা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পুলিশ স্টেশন",
  },
  {
    id: 56,
    Name: "ঘিওর থানা, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পুলিশ স্টেশন",
  },
  {
    id: 57,
    Name: "পাটুরিয়া ঘাট পুলিশ ফাঁড়ি",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পুলিশ স্টেশন",
  },
  {
    id: 58,
    Name: "শিবালয় থানা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পুলিশ স্টেশন",
  },
  {
    id: 59,
    Name: "সিঙ্গাইর থানা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পুলিশ স্টেশন",
  },
  {
    id: 60,
    Name: "দৌলতপুর থানা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পুলিশ স্টেশন",
  },
  {
    id: 61,
    Name: "সাটুরিয়া থানা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পুলিশ স্টেশন",
  },
  {
    id: 62,
    Name: "মানিকগঞ্জ পল্লী বিদ্যুৎ সমিতি, সদর দপ্তর",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 63,
    Name: "মানিকগঞ্জ পল্লী বিদ্যুৎ সমিতি, জোনাল অফিস",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 64,
    Name: "পল্লী বিদ্যুৎ সমিতি, গংগাধরপট্টি, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 65,
    Name: "বাংলাদেশহাট অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 66,
    Name: "কাটিগ্রাম অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 67,
    Name: "বালিরটেক অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 68,
    Name: "পালোড়া অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 69,
    Name: "৩৩/১১ কেভি গ্রীড উপকেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 70,
    Name: "চান্দহর অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 71,
    Name: "চারিগ্রাম অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 72,
    Name: "বাস্তা বাজার অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 73,
    Name: "জিয়নপুর অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 74,
    Name: "সিংগাইর জোনাল অফিস",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 75,
    Name: "গাড়াদিয়া বাজার অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 76,
    Name: "শিবালয় সাব-জোনাল অফিস",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 77,
    Name: "আরিচা এরিয়া জোনাল অফিস",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 78,
    Name: "ঝিটকা সাব-জোনাল অফিস",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 79,
    Name: "হরিরামপুর অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 80,
    Name: "ঘিওর জোনাল অফিস",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 81,
    Name: "দৌলতপুর সাব জোনাল অফিস",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 82,
    Name: "কলিয়া অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 82,
    Name: "সাটুরিয়া সাব-জোনাল অফিস",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 83,
    Name: "কান্দাপাড়া অভিযোগ কেন্দ্র",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পল্লি বিদ্যুৎ",
  },
  {
    id: 83,
    Name: "কানিজ ফাতেমা গার্লস স্কুল অ্যান্ড কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "সরকারি ঘিওর কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "বায়রা কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "বেতিলা উচ্চ বিদ্যালয় ও কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "এম এ রউফ কলেজ কৌরী",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "সাটুরিয়া সৈয়দ কালুশাহ কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "সরকারি ভিকু মেমোরিয়াল কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "মহাদেবপুর ইউনিয়ন সরকারি কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "ঝিটকা খাজা রহমত আলী কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "গোলাইডাঙ্গা মুক্তিযোদ্ধা স্মৃতি কলেজ",
    MobileNumber: "01578554454",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "তালুকনগর কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "ডা.আব্দুর রহিম খান মহিলা কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "বানিয়াজুরী ইউনিয়ন সরকারী স্কুল এন্ড কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "আফরোজা রমজান গার্লস স্কুল অ্যান্ড কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "গড়পাড়া হাফিজউদ্দিন কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "সরকারি বিচরপতি নুরুল ইসলাম কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "মুন্নু ইন্টারন্যাশনাল স্কুল অ্যান্ড কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "আদর্শ কলেজ খাবাশপুর",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "জিয়ানপুর বেলায়েত হোসেন কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "বাচামারা বাঘুটিয়া চরকাটারী কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "রমজান আলী কলেজ জয়রা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "গোলাম মনির হোসেন মহিলা কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "রাজীবপুর আদর্শ কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "রাওয়ান ইবনে রমজান স্কুল অ্যান্ড কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "বালিয়াটি কলেজ মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "খোন্দকার দেলোয়ার হোসেন কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "মতিলাল কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "শিবালয় সদরউদ্দিন কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "অক্সফোর্ড একাডেমি",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "তেরশ্রী কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "সিংগাইর কলেজ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },

  {
    id: 83,
    Name: "বেগম জরিনা কলেজ মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "কলেজ",
  },
  {
    id: 83,
    Name: "মানিকগঞ্জ ইসলামিয়া কামিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "বালিয়াটি দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "চররাজ নগর মানিকনগর মাহমুদিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "বাঘুটিয়া আলিম মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "ধল্লা ইসলামিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "ঘিওর সিনিয়র মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "দরগ্রাম ইসলামিয়া সিনিয়র মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "চর কালিকা পুর শুকরিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "চর জামালপুর ইসলামিয়া আলিম মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "আন্ধার মানিক ইসলামিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "গোলড়া ইসলামিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "ঘড়িয়ালা উম্মে কুলসুম দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "বনপারিল দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "দোয়াত আলী আলিম মাদ্রাসা, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "সরুপাই আলহাজ আব্দুল হালিম দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "সাহেব আলী খান মহিলা দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "কালিয়াকৈর ইসলামিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "দৌলতপুর দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "হাজী জহির উদ্দিন দারুস সালাম দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "তালুকনগর বোরহানিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "বৈকুণ্ঠপুর খাগড়াটা আহমদিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "কাজী সফিউদ্দিন দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "শিবালয় রশিদিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "খাসেরচর মাহমুদিয়া সিনিয়র মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "পাটিলা পাড়া এম.বি. দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "আলহাজ্ব প্রিন্সিপাল আবু বক্স খান কলন ট্রাস্ট ইসলামিয়া মহিলা মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "ফেচুয়া ধারা শাহ জোহিরিয়াদারুল উলুম ইসলামিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "ঝিটকা গাউসুল আজম আব্দুল কাদের জেলানী (র:) দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },
  {
    id: 83,
    Name: "ভাতিরচর গাউসিয়া সুন্নিয়া দাখিল মাদ্রাসা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "মাদ্রাসা",
  },

  {
    id: 83,
    Name: "উত্তরা ব্যাংক লিমিটেড, মানিকগঞ্জ শাখা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "আইএফআইসি ব্যাংক লিমিটেড, মানিকগঞ্জ শাখা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "ফার্স্ট সিকিউরিটি ইসলামী ব্যাংক মানিকগঞ্জ শাখা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "ইসলামী ব্যাংক বাংলাদেশ লিমিটেড মানিকগঞ্জ শাখা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "বাংলাদেশ কৃষি ব্যাংক, মানিকগঞ্জ শাখা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "ট্রাস্ট ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "অগ্রণী ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "মার্কেন্টাইল ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "জনতা ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "এক্সপোর্ট ইমপোর্ট ব্যাংক অব বাংলাদেশ লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "ডাচ-বাংলা ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "পূবালী ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "ইবিএল ৩৬৫",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "ইউনাইটেড কমার্শিয়াল ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "ব্র্যাক ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "শাহজালাল ইসলামী ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "অগ্রণী ব্যাংক",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "রূপালী ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "এনআরবিসি ব্যাংক লিমিটেড, মানিকগঞ্জ শাখা",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "সোনালী ব্যাংক লিমিটেড",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ব্যাংক",
  },
  {
    id: 83,
    Name: "বালিয়াটি জমিদার বাড়ি",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
    details: "বিস্তারিত",
  },
  {
    id: 83,
    Name: "তেওতা জমিদার বাড়ি",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
  },
  {
    id: 83,
    Name: "ধানকোড়া জমিদার বাড়ি",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
  },
  {
    id: 83,
    Name: "বেতিলা জমিদার বাড়ি",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
  },
  {
    id: 83,
    Name: "নাহার গার্ডেন",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
  },
  {
    id: 83,
    Name: "মত্ত মঠ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
  },
  {
    id: 83,
    Name: "চান্দরার সরিষাক্ষেত",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
  },
  {
    id: 83,
    Name: "ফলসাটিয়া খামার বাড়ী, শিবালয়",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
  },
  {
    id: 83,
    Name: "শহীদ রফিক স্মৃতি যাদুঘর, সিঙ্গাইর",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
  },
  {
    id: 83,
    Name: "পোদ্দার বাড়ী, হরিরামপুর",
    MobileNumber: "01xxxxxxxxxxx",
    token: "পর্যটন কেন্দ্র",
  },
  {
    id: 83,
    Name: "সিটি হাসপাতাল এন্ড ডায়াগনস্টিক সেন্টার",
    MobileNumber: "01718514389",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "জম জম জেনারেল হাসপাতাল, মানিকগঞ্জ",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "জনতা নার্সিং হোম",
    MobileNumber: "01819440473",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "কালিয়ান্দি কমিউনিটি ক্লিনিক",
    MobileNumber: "01715393891",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "ডক্টরস্ ক্লিনিক",
    MobileNumber: "01715781409",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "মেরী স্টোপেজ ক্লিনিক",
    MobileNumber: "01714642882",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "মেডিকেল ক্লিনিক ডায়াগনস্টিক সেন্টার",
    MobileNumber: "01712004238",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "মুন্নু মেডিকেল কলেজ এন্ড হাসপাতাল",
    MobileNumber: "01648874848",
    token: "হাসপাতাল",
  },
  {
    id: 14,
    Name: "মা ও শিশু ওয়েলফেয়ার ক্লিনিক",
    MobileNumber: "01725783717",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "মাদার কেয়ার হোম",
    MobileNumber: "01711986114",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "নিউ জননী ক্লিনিক",
    MobileNumber: "01914307515",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "পারিবারিক স্বাস্থ্য ক্লিনিক",
    MobileNumber: "01711201269",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "সাটুরিয়া নার্সিং হোম",
    MobileNumber: "01711394323",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "সুস্বাস্থ্য হেলথ কেয়ার",
    MobileNumber: "01711859988",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "নিউ স্কয়ার ক্লিনিক",
    MobileNumber: "01713572309",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "আল রাফি মেডিকেল সেন্টার",
    MobileNumber: "01715781409",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "পেইন প্যারালাইসিস স্পেশালাইজড এন্ড জেনারেল হাসপাতাল",
    MobileNumber: "01790162885",
    token: "ক্লিনিক",
  },
  {
    id: 14,
    Name: "এশিয়ান মেডিকেল সেন্টার",
    MobileNumber: "01xxxxxxxxxxx",
    token: "ক্লিনিক",
  },
];
